remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: Ramblings Of a Network Engineer
description: Things I find interesting whilst levelling up my skills

show_downloads: true
google_analytics: 4424899486

github:
  
